#!/bin/sh

# Fixes up all file patches (in IntelliJ, right-click -> Run 'fixup')

cd ../..
./gradlew :spout-paper:fixupPaperApiFilePatches || true
./gradlew :spout-paper:spout-server:fixupMinecraftResourcePatches || true
./gradlew :spout-paper:spout-server:fixupMinecraftSourcePatches || true
./gradlew :spout-paper:spout-server:fixupPaperServerFilePatches || true
cd spout-paper/gradle-bin
